---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: production
  labels:
    app: podinfo
  annotations:
    flux.weave.works/tag.podinfod: semver:~1.5
    flux.weave.works/automated: 'true'
    flux.weave.works/locked_user: Arnaud Rebts <arnaud.rebts@gmail.com>
    flux.weave.works/locked: 'true'
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        image: arnaudrebts/k8s-podinfo:v1.6.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9898
          name: http
          protocol: TCP
        command:
        - ./podinfo
        - --port=9898
        - --level=info
        - --random-delay=false
        - --random-error=false
        env:
        - name: PODINFO_UI_COLOR
          value: blue
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9898
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9898
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 64Mi
