apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: ingress
spec:
  releaseName: traefik
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: traefik
    version: 1.67.1
  values:
    kubernetes:
      ingressEndpoint:
        useDefaultPublishedService: true
